### ISSUE TITLE
Не закреплена шапка сайта

### ISSUE THREAD

**Issue by originalskobka** [originalskobka/T-code#16]
**Шаги выполнения** 

1. Перейти на страницу -  https://true-denis.tw1.ru/
2. Начать скроллить страницу вниз

**Ожидаемый результат**:  Шапка закреплена, будет постоянно видна

**Фактический результат:**  Шапка не закреплена

![Image](https://user-images.githubusercontent.com/121563260/233024686-fe0e4927-2927-4f8d-b7d0-d2a4d189cd82.png)

**Comment by Hodache** [comment]
В прототипе шапка не закреплена, письменных упоминаний об этом тоже не нашел

**Comment by originalskobka** [comment]
@Hodache Дефолтное состояние для шапки в t-code. Согласовано с Иваном
