### ISSUE TITLE
Элементы "Награды", "Кейсы" и "Ивенты" не имеют анимации на странице "Кто мы?"

### ISSUE THREAD

**Issue by originalskobka** [originalskobka/T-code#2]
**Шаги выполнения** 

1. Перейти на страницу - https://true-denis.tw1.ru/about.html

**Ожидаемый результат**:  Все элементы будут с анимацией, как элемент "True.code"

**Фактический результат:**  Элементы "Награды", "Кейсы" и "Ивенты" не имеют анимации

**Comment by Hodache** [comment]
В интерактивной версии прототипа элементы "Награды", "Кейсы" и "Ивенты" не анимированы

**Comment by originalskobka** [comment]
@Hodache Перенеси карточку в блок "На обсуждении" и уточни у Ивана. 

Мне давалась инфа, что анимация д.б.
