### ISSUE TITLE
При уменьшении разрешения браузера в шапке появляется Email, которого до этого не было на странице

### ISSUE THREAD

**Issue by originalskobka** [originalskobka/T-code#4]
**Шаги выполнения** 

1. Перейти на страницу - https://true-denis.tw1.ru/about.html
2. Уменьшать браузер до разрешения 1023px

**Ожидаемый результат**:  при уменьшении разрешения браузера новые элементы не появляются, имеющиеся скрываются

**Фактический результат:**  при уменьшении разрешения браузера появляется Емаил, который нигде до этого не отображался (на странице и макете найти его не удалось), вновь появляется номер телефона. Происходит смещение навигационных элементов вниз.

![Image](https://user-images.githubusercontent.com/121563260/232956244-b76cadf2-fcea-4026-ac2c-ba923df8b32b.png)

**Comment by Hodache** [comment]
В мобильной версии есть email

**Comment by originalskobka** [comment]
@Hodache Привет!

Да, уже увидел, забыл поправить коммент. Но в данном случае  должно появиться бургер-меню, в которое уйдут "Вакансии", "Кто мы?" и т.д

Чтобы адекватно выглядело и не происходило смещение, которое бросается в глаза

**Comment by originalskobka** [comment]
@Hodache 

**Шаги воспроизведения:**

1. Открыть сайт
2. Уменьшить разрешение  до появления бургер-меню 
3. Открыть бургер-меню
4. Закрыть бургер-меню
5. Увеличить разрешение браузера 

Ожидаемый: После увеличения разрешения браузера, бургер-меню пропадет, все элементы будут отображаться в шапке

Фактический: Бургер-меню пропадает, ничего кроме телефона не отображается



![Image](https://github.com/originalskobka/T-code/assets/121563260/bddbd8fa-68fa-4bea-a856-711e8e53533f)
